### ISSUE TITLE
OSError: [WinError -2147417850]

### ISSUE THREAD

**Issue by kudmich** [mrob95/pyvda#19]
when trying to use `pyvda.get_virtual_desktops()`
I encountered a problem:

```
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Mich\Desktop\TT\wb.py", line 7, in <module>
    from pyvda import get_virtual_desktops
  File "C:\Users\Mich\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyvda\__init__.py", line 51, in <module>
    from .pyvda import (
  File "C:\Users\Mich\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyvda\pyvda.py", line 24, in <module>
    managers = Managers()
  File "C:\Users\Mich\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyvda\utils.py", line 53, in __init__
    self.manager_internal = get_vd_manager_internal()
  File "C:\Users\Mich\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyvda\utils.py", line 40, in get_vd_manager_internal
    return _get_object(IVirtualDesktopManagerInternal, CLSID_VirtualDesktopManagerInternal)
  File "C:\Users\Mich\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyvda\utils.py", line 24, in _get_object
    CoInitialize()
  File "C:\Users\Mich\AppData\Local\Programs\Python\Python38-32\lib\site-packages\comtypes\__init__.py", line 150, in CoInitialize
    return CoInitializeEx(COINIT_APARTMENTTHREADED)
  File "C:\Users\Mich\AppData\Local\Programs\Python\Python38-32\lib\site-packages\comtypes\__init__.py", line 156, in CoInitializeEx
    _ole32.CoInitializeEx(None, flags)
  File "_ctypes/callproc.c", line 998, in GetResult
OSError: [WinError -2147417850] Po ustawieniu trybu wątku nie można go zmienić

Process finished with exit code 1
```
Translate: "OSError: [WinError -2147417850] Po ustawieniu trybu wątku nie można go zmienić" -> Once the thread mode is set, it cannot be changed

**Comment by mrob95** [comment]
From the [docs](https://learn.microsoft.com/en-us/windows/win32/api/combaseapi/nf-combaseapi-coinitializeex):
> After the concurrency model for a thread is set, it cannot be changed. A call to [CoInitialize](https://learn.microsoft.com/en-us/windows/desktop/api/objbase/nf-objbase-coinitialize) on an apartment that was previously initialized as multithreaded will fail and return RPC_E_CHANGED_MODE.

We call `comtypes.CoInitialize` which initialises COM with `COINIT_APARTMENTTHREADED` concurrency mode. It looks like something else in your program is initialising it before we do with `COINIT_MULTITHREADED`. This is definitely a bug in pyvda since I don't think we care what the concurrency mode is as long as com is initialised.

I'm curious to know what is causing this though. What context are you using pyvda in? Are there any other libraries involved that might be calling `CoInitialize`?

**Comment by kudmich** [comment]
In this scope im using `from pywinauto.application import Application`, probably this package is causing the problem with the `pyvda`

**Comment by mrob95** [comment]
> In this scope im using `from pywinauto.application import Application`, probably this package is causing the problem with the `pyvda`

That makes sense. Looking at this code:
https://github.com/pywinauto/pywinauto/pull/450/files

It looks like pywinauto prefers COINIT_MULTITHREADED but will fall back to apartment threaded if com is already initialised. I've made a couple of changes to fix these issues:
* Use `CoInitializeEx` instead of `CoInitialize`. This will respect the sys.coinit_flags variable that pywinauto sets if it runs first.
* Log and ignore errors from `CoInitializeEx`. This fixes the case where com has been initialised multithreaded but the sys.coinit_flags variable has not been set.

It's still a little awkward because if pyvda is imported first then it will initialise with COINIT_APARTMENTTHREADED, whereas pywinauto would prefer COINIT_MULTITHREADED. I'm not sure if there is anything I can do about this. It may be worth setting `sys.coinit_flags = COINIT_MULTITHREADED` before importing either library, or making sure that you import pywinauto before pyvda.

**Comment by mrob95** [comment]
Could you test again on the latest version of pyvda? Should be fixed.

**Comment by kudmich** [comment]
@mrob95 At first glance, your fix seems to be working fine! Thank you for your work.

**Comment by mrob95** [comment]
Awesome, thanks for the report, let me know if you come across any other issues 👍
