### ISSUE TITLE
TypeError when creating desktop

### ISSUE THREAD

**Issue by Dylgod** [mrob95/pyvda#24]
Platform version: 10.0.22621

Error log:

```Python
Traceback (most recent call last):
  File "c:\Users\crtkd\OneDrive\Documents\Python Code\desktest.py", line 161, in <module>
    dest_dsk = pyvda.VirtualDesktop.create()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\crtkd\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyvda\pyvda.py", line 295, in create
    desktop = managers.manager_internal.CreateDesktopW(*NULL_IF_OVER_20231)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: call takes exactly 1 arguments (2 given)
```

**Comment by mrob95** [comment]
Could you give `0.3.0` a try and see if this fixes it?

**Comment by Dylgod** [comment]
It worked like a charm. You're a legend, thanks.

**Comment by mrob95** [comment]
No worries! Glad you find it useful.
