### ISSUE TITLE
Create desktop error

### ISSUE THREAD

**Issue by markox92** [mrob95/pyvda#51]
```
from pyvda import VirtualDesktop
VirtualDesktop.create()
```

It's back error

```
Traceback (most recent call last):
  File "C:\Users\marko\Desktop\xx.py", line 2, in <module>
    VirtualDesktop.create()
  File "C:\Users\marko\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pyvda\pyvda.py", line 305, in create
    desktop = managers.manager_internal.create_desktop() # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marko\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pyvda\com_defns.py", line 320, in create_desktop
    return self.CreateDesktopW() # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^
OSError: exception: access violation reading 0x0000000000000000
```

Windows 11 Pro
Ver: 24H2
Build: 26100.2454
Python 3.12.7

**Comment by mrob95** [comment]
Thanks for reporting this. I don't have a machine to test on but could you try version 0.5.0 and see if this solves the problem?

**Comment by markox92** [comment]
> Thanks for reporting this. I don't have a machine to test on but could you try version 0.5.0 and see if this solves the problem?

Thank you, it's working now, just a question: I have found some fork of pyvda where it is possible to call `VirtualDesktop(2).go(animation=True)` and switch desktop with animation, maybe you can also include this?

**Comment by mirober** [comment]
> > Thanks for reporting this. I don't have a machine to test on but could you try version 0.5.0 and see if this solves the problem?
> 
> Thank you, it's working now, just a question: I have found some fork of pyvda where it is possible to call `VirtualDesktop(2).go(animation=True)` and switch desktop with animation, maybe you can also include this?

It is not implemented in the `VirtualDesktop` class but you can look at https://github.com/mirober/pyvda/blob/master/pyvda/com_defns.py and see that there are `SwitchDesktopWithAnimation` methods available, at least on later versions.

If you would like to create a PR to add this that would be great. I personally find that the animations make things feel very slow, but I'm happy to support it.

**Comment by mirober** [comment]
Closing in favour of #50
